---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mystok-gcp-k8s
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: mystok-gcp-k8s
  validation: client

